name: Delete Old Workflow Runs and Artifacts

on:
  schedule:
    - cron: '0 3 * * *'  # Every day at 3am UTC
  workflow_dispatch:      # Allow manual run if needed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 2
          keep_minimum_runs: 1

      - name: Delete old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '2 days'                  # Match retain_days
          skip-recent: 1                # Keep artifacts for the most recent run
          token: ${{ secrets.GITHUB_TOKEN }}
